# Linear Regression : Single-variable

In [1]:
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: ignored

In [ ]:
x_data = np.array([1,2,3,4,5]).reshape(5,1)
t_data = np.array([2,3,4,5,6]).reshape(5,1)

print("X_data = ", x_data.shape, ", t_data.shape = ", t_data.shape)
print(x_data)

X_data =  (5, 1) , t_data.shape =  (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
W = np.random.rand(1, 1)
b = np.random.rand(1)

print('W = ', W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.29237656]] , W.shape =  (1, 1) , b =  [0.77018661] , b.shape =  (1,)


In [ ]:
def loss_func(x, t):
  y = np.dot(x, W) + b

  return (np.sum((t-y)**2)) / len(x)

In [ ]:
def numerical_derivative(f, x):
  delta_x = 1e-4
  grad = np.zeros_like(x)

  it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])

  while not it.finished:
    idx = it.multi_index
    tmp_val = x[idx]
    x[idx] = float(tmp_val) + delta_x
    fx1 = f(x)

    x[idx] = tmp_val - delta_x
    fx2 = f(x)
    grad[idx] = (fx1 - fx2) / (2 * delta_x)

    x[idx] = tmp_val
    it.iternext()
  return grad

In [ ]:
def error_val(x, t):
  y = np.dot(x, W) + b
  return (np.sum((t-y)**2)) / len(x)

def predict(x):
  y = np.dot(x, W) + b
  return y

In [ ]:
learning_rate = 1e-3
f = lambda x : loss_func(x_data, t_data)

print('Initial error value = ', error_val(x_data, t_data))
print('Initial W = ', W, ', b = ', b)

for step in range(10001):
  W -= learning_rate * numerical_derivative(f, W)
  b -= learning_rate * numerical_derivative(f, b)

  if (step % 400 == 0):
    print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ", b)

Initial error value =  6.536582545643272
Initial W =  [[0.29237656]] , b =  [0.77018661]
step =  0 error value =  6.231381737541334 W =  [[0.30932315]] , b =  [0.7747903]
step =  400 error value =  0.00017445765114259087 W =  [[1.00852549]] , b =  [0.96903004]
step =  800 error value =  0.00013303126256654336 W =  [[1.00748832]] , b =  [0.97296542]
step =  1200 error value =  0.00010145782377719433 W =  [[1.00653959]] , b =  [0.97639057]
step =  1600 error value =  7.737797710856347e-05 W =  [[1.00571106]] , b =  [0.97938177]
step =  2000 error value =  5.901320488167531e-05 W =  [[1.00498749]] , b =  [0.981994]
step =  2400 error value =  4.500709995972512e-05 W =  [[1.0043556]] , b =  [0.98427527]
step =  2800 error value =  3.432518282723799e-05 W =  [[1.00380377]] , b =  [0.98626752]
step =  3200 error value =  2.6178495774618796e-05 W =  [[1.00332185]] , b =  [0.98800735]
step =  3600 error value =  1.9965331123532645e-05 W =  [[1.00290099]] , b =  [0.98952676]
step =  4000 error 

In [ ]:
predict(43)

array([[44.01307929]])

>> ### 실습. 위 데이터를 예측을 잘 할 수 있도록, learning_rate 및 step을 수정해 볼 것.

# Linear Regression : Multi-variable

In [ ]:
import numpy as np

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/2021_2학기_데이터분석과머신러닝/LinearRegression_LogisticRegression

/content/drive/MyDrive/Colab Notebooks/2021_2학기_데이터분석과머신러닝/LinearRegression_LogisticRegression


In [ ]:
!dir

data-01-test-score.csv		    RFMiD_Test_SET.csv
Linear_Regression.ipynb		    RFMiD_Train_SET.csv
Logistic_Regression_실습모드.ipynb


In [ ]:
loaded_data = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = loaded_data[:, 0:-1]
t_data = loaded_data[:, [-1]]

print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape)

x_data.ndim =  2 , x_data.shape =  (25, 3)
t_data.ndim =  2 , t_data.shape =  (25, 1)


In [ ]:
W = np.random.rand(3, 1)
b = np.random.rand(1)

print('W = ', W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.71020852]
 [0.2110497 ]
 [0.62697213]] , W.shape =  (3, 1) , b =  [0.10349584] , b.shape =  (1,)


In [ ]:
def loss_func(x, t):
  y = np.dot(x, W) + b

  return (np.sum((t-y)**2)) / len(x)

In [ ]:
def numerical_derivative(f, x):
  delta_x = 1e-4
  grad = np.zeros_like(x)

  it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])

  while not it.finished:
    idx = it.multi_index
    tmp_val = x[idx]
    x[idx] = float(tmp_val) + delta_x
    fx1 = f(x)

    x[idx] = tmp_val - delta_x
    fx2 = f(x)
    grad[idx] = (fx1 - fx2) / (2 * delta_x)

    x[idx] = tmp_val
    it.iternext()
  return grad

In [ ]:
def error_val(x, t):
  y = np.dot(x, W) + b
  return (np.sum((t-y)**2)) / len(x)

def predict(x):
  y = np.dot(x, W) + b
  return y

In [ ]:
learning_rate = 1e-7
f = lambda x : loss_func(x_data, t_data)

print('Initial error value = ', error_val(x_data, t_data))
print('Initial W = ', W, ', b = ', b)

for step in range(100001):
  W -= learning_rate * numerical_derivative(f, W)
  b -= learning_rate * numerical_derivative(f, b)

  if (step % 400 == 0):
    print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ", b)

In [ ]:
test_data = np.array([100, 98, 81])
predict(test_data)

array([185.5887024])

>> ### 실습. 위 코드에서 학습률이 1e-5일 때, 10,000 step을 한 경우와, 1e-3일 때, 10,000과 50,000 step을 진행한 경우의 결과를 확인하라.

In [ ]:
learning_rate = 1e-7
for step in range(100001):
array([185.5887024])