In [1]:
import numpy as np
import cv2

In [5]:
one_dman = np.array([0, 0])
one_dman

array([0, 0])

In [7]:
two_dman = np.array([one_dman, one_dman])
two_dman

array([[0, 0],
       [0, 0]])

In [12]:
three_temp_dman = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
three_temp_dman

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
three_dman = np.array([[three_temp_dman], [three_temp_dman], [three_temp_dman]])
three_dman

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [ ]:
randint = np.random.randint(9, )